//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int Id { get; set; }
        public int CollectionType { get; set; }
        public int CollectionStatus { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public Nullable<System.TimeSpan> CollectionLastTime { get; set; }
        public int FoodType { get; set; }
        public int RestaurantId { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual RestaurantBranch RestaurantBranch { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
